on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Node 20.17.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.17.0

      - name: Install and build
        run: |
          npm i
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ftp.ibrahima-sourabie.com
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/videoflix_frontend/browser/
          server-dir: /videoflix.ibrahima-sourabie.com/
          delete: true
          log-level: verbose

      - name: 📂 Upload .htaccess and Robots.txt
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ftp.ibrahima-sourabie.com
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /videoflix.ibrahima-sourabie.com/
          include: ".htaccess,Robots.txt"
          log-level: verbose
